owncloud/ocis-accounts

- changelog/unreleased/remove-timezone-setting.md
- pkg/service/v0/settings.go
We will not make use of the timezone setting in the very near future, so it would be confusing for a user to have this setting in their settings UI. Removing it until we use the timezone in ocis-web.
> Remove timezone setting

- pkg/provider/bleve.go
- pkg/service/v0/service.go
- handle terms as keywords to not deconstruct emails into individual parts
- unescape string terms
> handle terms as keywords, remove quotes

- pkg/service/v0/service.go
Fixes https://github.com/owncloud/ocis-accounts/issues/39
Signed-off-by: Jörn Friedrich Dreyer <jfd@butonic.de>
> create default accounts when dir does not exist

- changelog/unreleased/change-grpc-error-messages.md
- pkg/service/v0/service.go
Add more information to error responses.
I followed the micro example here: https://m3o.com/docs/go-errors.html
Closes https://github.com/owncloud/ocis-accounts/issues/11
> change grpc api errors

- .drone.star
- sonar-project.properties
only set pullrequest config if the build was triggered by a pull request
> tweak sonar config

- changelog/unreleased/fix-indexing.md
- pkg/service/v0/accounts.go
- pkg/service/v0/groups.go
This also fixes that on Create and Update calls the index was not
updated properly.
Alternative approach for https://github.com/owncloud/ocis-accounts/pull/58
> Refactor indexing of new entities into own function

- changelog/unreleased/fix-account-group-id.md
- pkg/service/v0/groups.go
The accountId and GroupId were swapped when removing the member from a group after deleting
the group. That was fixed  in this PR.
> Fix the account and group id mismatch in delete group method

- .gitignore
- go.mod
- go.sum
- pkg/proto/v0/accounts.pb.micro_test.go
Add gRPC integration tests for accounts and group related actions for
-  CreateAccount
- ListAccounts
- GetAccount
- UpdateAccount
- DeleteAccount
- ListGroup
- AddGroup
- DeleteGroup
- GetGroup
- UpdateGroup(not implemented)
- AddMember
- ListMembers
- RemoveMembers
fixes #29
> [Tests-Only] Add tests for gRPC

- changelog/unreleased/fix-segfault.md
- changelog/unreleased/tighten-screws.md
- pkg/proto/v0/accounts.pb.micro_test.go
- pkg/service/v0/accounts.go
Passwords are stored in a dedicated child struct of an account. We fixed several segfault conditions where the methods would try to unset a password when that child struct was not existing.
> fix password related segfaults

- changelog/unreleased/fix-int-queries.md
- pkg/provider/bleve.go
partly fixes https://github.com/owncloud/ocis-glauth/issues/28 by using the correct min & max numeric queries from bleve
> fix int parsing

- changelog/unreleased/add-write-mutexes.md
- pkg/service/v0/accounts.go
- pkg/service/v0/groups.go
Concurrent account or groups writes would corrupt the json file on disk, because the different goroutines would be treated as a single thread from the os. We introduce a mutex for account and group file writes each. This locks the update frequency for all accounts/groups and could be further improved by using a concurrent map of mutexes with a mutex per account / group. PR welcome.
> Add write mutexes

- changelog/unreleased/fix-index-mapping.md
- pkg/provider/bleve.go
- pkg/service/v0/accounts.go
- pkg/service/v0/groups.go
- pkg/service/v0/service.go
The index mapping was not being used because we were not using the right blevesearch TypeField, leading to username like properties like `preferred_name` and `on_premises_sam_account_name` to be case sensitive.
fixes https://github.com/owncloud/ocis-accounts/issues/73
1. `ACCOUNTS_LOG_LEVEL=debug go run cmd/ocis-accounts/main.go server`
2. `micro call com.owncloud.api.accounts AccountsService.ListAccounts "{\"query\":\"preferred_name eq 'einstein'\"}"`
3. `micro call com.owncloud.api.accounts AccountsService.ListAccounts "{\"query\":\"preferred_name eq 'EiNsTeIn'\"}"`
both calls should return the account.
> fix index mapping

- changelog/unreleased/fix-prefix-query.md
- pkg/provider/bleve.go
Prefix queries also need to unescape token values like `'some ''ol string'` to `some 'ol string` before using it in a prefix query
> Unescape value for prefix query

- changelog/unreleased/atomic-requests.md
- pkg/service/v0/accounts.go
- pkg/service/v0/groups.go
This PR is probably the equivalent of using a cannon to exterminate a fly. It makes every request to the provisioning API atomic, this way operations on the file system level are ensured to be atomic, and not bothered by any other request.
```
make test-acceptance-api TEST_SERVER_URL=https://localhost:9200 TEST_OCIS=true OCIS_REVA_DATA_ROOT=/var/tmp/reva/ SKELETON_DIR=apps/testing/data/apiSkeleton BEHAT_FILTER_TAGS='~@skipOnOcis&&~@skipOnOcis-OC-Storage' TESTING_REMOTE_SYSTEM=true BEHAT_FEATURE=tests/acceptance/features/apiShareManagementBasic/createShare.feature
```
> Atomic requests to the accounts service

- changelog/unreleased/add-language-permissions-to-default-roles.md
- go.mod
- go.sum
- pkg/service/v0/settings.go
We have default roles in ocis-settings and the respective bundle uuids are exposed there as constants. This PR adds permissions for the language to the default roles. We're not filtering for those, though, so this is only setting up the data basis for permission filtering later on.
> Add permissions for roles

- .drone.star
There are weird issues where randomly protoc compilations happen
although they should not be triggered. As those don't run through the
makefile but somehow differently, the prerequisites are not built first
(protoc plugins have to be fetched, which happens in the `make
protobuf` step).
> Explicitly run `make protobuf` when running `make build`

- .drone.star
Was needed to be on a branch to get a PR in ocis-accounts merged. Since
that is done and updated in ocis, we can now switch the tests back to
ocis master.
> [tests only] Change ocis for tests back to master

- changelog/unreleased/builtin-regular-users.md
- changelog/unreleased/new-admin-user.md
- go.mod
- go.sum
- pkg/proto/v0/accounts.pb.micro_test.go
- pkg/service/v0/option.go
- pkg/service/v0/service.go
This PR adds a new default user "Maurice Moss" with credentials `moss:vista`. It also assigns the default `user` role to `einstein`, `marie` und `richard` and the default `admin` role to the new `moss` user.
> Add default user moss and assign default roles to builtin users

- changelog/unreleased/change-hashing-algorithm.md
- pkg/service/v0/accounts.go
- pkg/service/v0/service.go
- ui/tests/acceptance/pageobjects/accountsPage.js
Even though SHA-512 is currently considered a secure algorithm it is not the best choice for password hashing. As this change introduces a breaking change it is beast to introduce it as early as possible to prevent us from having to implement a migration strategy.
> change hashing algorithm from SHA-512 to bcrypt

- .drone.star
Because internal drone does not yet have ARM agents available.
And remove `sonarcloud` step - it was done as a POC, and would need the various secrets... set up.
> [Tests-Only] Disable ARM builds
